### ISSUE TITLE
request: Add examples for result

### ISSUE THREAD

**Issue by gc** [sapphiredev/utilities#647]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Add examples for https://github.com/sapphiredev/utilities/tree/main/packages/result 

this is a similar library which gives lots of examples: https://github.com/traverse1984/oxide.ts . doesn't have to be as much as this one has, but just some basic examples covering the main api.

### Desired solution

N/A

### Alternatives considered

N/A

**Comment by kyranet** [comment]
The reason why I didn't include them in the README.md is because they're already very heavily documented in the respective interfaces:

https://github.com/sapphiredev/utilities/blob/90ac3fc55d19a0fae1180af4dd1754dc7a669ef4/packages/result/src/lib/Result/IResult.ts
https://github.com/sapphiredev/utilities/blob/90ac3fc55d19a0fae1180af4dd1754dc7a669ef4/packages/result/src/lib/Option/IOption.ts

Those should show up in IntelliSense (at least they did for me), are you suggesting to copy them to the README.md (probably with [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details))?

**Comment by gc** [comment]
Just some basic examples so we can get the general idea of the library.

**Comment by favna** [comment]
Examples are on the TSDoc, and TSDoc is generated to markdown to HTML on our website so instead of duplicating in 2 places I added a link to the website: https://www.sapphirejs.dev/docs/Documentation/api-utilities/interfaces/sapphire_result.IResult
