### ISSUE TITLE
request: New decorators for subcommands

### ISSUE THREAD

**Issue by Xenofic** [sapphiredev/utilities#655]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

As we know the Command.Options have a lot of options which the subcommand lacks so with the help of decorators we can replicate this, it would be great to see this implemented all the Command.Options in the form of decorators for the subcommands.

### Desired solution

As i mentioned with the help of decorators, we already have some like RequiredClientPermissions and RequiredUserPermissions, these decorators function same as the Command.Options#RequiredClientPermissions and Command.Options#RequiredUserPermissions.

### Alternatives considered

Alternative solution can be is to add the CommandOptions to the SubCommandMappingOptions.

### Additional context

N/A.

**Comment by favna** [comment]
`@sapphire/decorators` is not to depend on `@sapphire/plugin-subcommands` because the latter is  a plugin, and `@sapphire/plugin-subcommands` won't get decorators because the Sapphire mentality is that code should work with both JS and TS.

Once Node ships a stable version of ES decorators in an LTS version (so an even number like 18, 20, 22, etc, not uneven like 19, 21, etc) they will be added to the `@sapphire/plugin-subcommands` code. That said, if anything this issue should be created on the plugins monorepo, but I'm closing this issue as "not planned" for now because it's unclear when ES decorators will ship to a stable version of Node.

Also as a last note, @kaname-png has their own plugin that we list on [awesome-sapphire](https://github.com/sapphiredev/awesome-sapphire/) which does have decorators: https://github.com/sawa-ko/neko-plugins/tree/main/packages/subcommands-advanced
